Do not install desktop integration if a number of conditions is met

diff --git a/desktopintegration b/desktopintegration
--- a/desktopintegration
+++ b/desktopintegration
@@ -26,6 +26,21 @@ fi
 # such as desktop integration daemons
 VENDORPREFIX=appimagekit
 
+FILENAME=$(readlink -f "${0}")
+
+echo $FILENAME
+
+if [[ "$FILENAME" != *.wrapper ]] ; then
+  echo "$0 is not named correctly. It should be named \$Exec.wrapper"
+  exit 0
+fi
+
+BIN=$(echo "$FILENAME" | sed -e 's|.wrapper||g')
+if [[ ! -f $BIN ]] ; then
+  echo "$BIN not found"
+  exit 0
+fi
+
 trap atexit EXIT
 
 atexit()
@@ -52,42 +67,49 @@ yesno()
   TITLE=$1
   TEXT=$2
   if [ -x /usr/bin/zenity ] ; then
-    LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" || SKIP=1
+    LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" || exit 0
   elif [ -x /usr/bin/kdialog ] ; then
-    LD_LIBRARY_PATH="" kdialog --caption "Disk auswerfen?" --title "$TITLE" -yesno "$TEXT" || SKIP=1
+    LD_LIBRARY_PATH="" kdialog --caption "Disk auswerfen?" --title "$TITLE" -yesno "$TEXT" || exit 0
   elif [ -x /usr/bin/Xdialog ] ; then
-    LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || SKIP=1
+    LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || exit 0
   else
     echo "zenity, kdialog, Xdialog missing. Skipping $0."
-    SKIP=1
+    exit 0
   fi
 }
+
+check_prevent()
+{
+  FILE=$1
+  if [ -e "$FILE" ] ; then
+    exit 0
+  fi
+}
+
+# Exit immediately of one of these files is present
+# (e.g., because the desktop environment wants to handle desktop integration itself)
+check_prevent "$HOME/.local/share/$VENDORPREFIX/no_desktopintegration"
+check_prevent "/usr/share/$VENDORPREFIX/no_desktopintegration"
+check_prevent "/etc/$VENDORPREFIX/no_desktopintegration"
+
+# Exit immediately if appimaged is running
+pidof appimaged 2>/dev/null && exit 0
+
+# Exit immediately if $DESKTOPINTEGRATION is not empty
+if [ ! -z "$DESKTOPINTEGRATION" ] ; then
+  exit 0
+fi
 
 check_dep()
 {
   DEP=$1
   if [ -z $(which $DEP) ] ; then
     echo "$DEP is missing. Skipping $0."
-    SKIP=1
+    exit 0
   fi
 }
 
-FILENAME=$(readlink -f "${0}")
-
-echo $FILENAME
-
-if [[ "$FILENAME" != *.wrapper ]] ; then
-  echo "$0 is not named correctly. It should be named \$Exec.wrapper"
-  SKIP=1
-fi
-
-BIN=$(echo "$FILENAME" | sed -e 's|.wrapper||g')
-if [[ ! -f $BIN ]] ; then
-  echo "$BIN not found"
-  SKIP=1
-fi
-
-DIRNAME=$(dirname $(readlink -f "${0}"))
+DIRNAME=$(dirname $FILENAME)
 
 # Check whether dependencies are present in base system (we do not bundle these)
 # http://cgit.freedesktop.org/xdg/desktop-file-utils/
@@ -100,12 +122,12 @@ DESKTOPFILE_NAME=$(basename $DESKTOPFILE)
 
 if [ ! -f "$DESKTOPFILE" ] ; then
   echo "Desktop file is missing. Please run $0 from within an AppImage."
-  SKIP=1
+  exit 0
 fi
 
 if [ -z "$APPIMAGE" ] ; then
   echo "\$APPIMAGE is missing. Please run $0 from within an AppImage."
-  SKIP=1
+  exit 0
 fi
 
 # Construct path to the icon according to
@@ -116,7 +138,7 @@ MD5=$(echo -n $ICONURL | md5sum | cut -c -32)
 ICONFILE="$HOME/.cache/thumbnails/normal/$MD5.png"
 if [ ! -f "$ICONFILE" ] ; then
   echo "$ICONFILE is missing. Please run $0 from within an AppImage."
-  SKIP=1
+  exit 0
 fi
 
 # $XDG_DATA_DIRS contains the default paths /usr/local/share:/usr/share
@@ -124,7 +146,7 @@ fi
 # of one of the $XDG_DATA_DIRS components
 if [ -z "$XDG_DATA_DIRS" ] ; then
   echo "\$XDG_DATA_DIRS is missing. Please run $0 from within an AppImage."
-  SKIP=1
+  exit 0
 fi
 
 # Determine where the desktop file should be installed
@@ -144,7 +166,7 @@ if [ -e "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME" ] ; then
   EXEC=$(grep "^Exec=" "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME" | head -n 1)
   # echo $EXEC
   if [ "Exec=$APPIMAGE" == "$EXEC" ] ; then
-    SKIP=1
+    exit 0
   fi
 fi
 
@@ -171,6 +193,5 @@ if [ -z "$SKIP" ] ; then
     --set-key=X-AppImage-Comment --set-value="Generated by $0" \
     --set-icon=$ICONFILE --set-key=TryExec --set-value=$APPIMAGE $DESKTOPFILE \
     --dir "$DESTINATION_DIR_DESKTOP"
+  xdg-desktop-menu forceupdate
 fi
-
-xdg-desktop-menu forceupdate
