Fix command existence check

diff --git a/desktopintegration b/desktopintegration
--- a/desktopintegration
+++ b/desktopintegration
@@ -147,11 +147,13 @@ check_prevent()
 
 check_dep()
 {
-  DEP=$1
-  if [ -z $(which $DEP 2>&1 1>/dev/null) ] ; then
-    log "$DEP is missing. Skipping ${THIS}."
-    exit 0
+  set +e
+  which $1 &>/dev/null
+  if [ $? -ne 0 ]; then
+    log "$1 is missing. Skipping ${THIS}."
+    exit 
   fi
+  set -e
 }
 
 # Determine where the desktop file should be installed
